import Vue from 'vue'
import { Button, Icon, Tabbar, TabbarItem, NavBar, Search, Swipe, SwipeItem, Rate, ActionSheet, Empty, Dialog, Radio, RadioGroup, Checkbox, Field, Form, Picker, Popup } from 'vant'
Vue.use(Button)
Vue.use(Icon)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Search)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Rate)
Vue.use(ActionSheet)
Vue.use(Empty)
Vue.use(Dialog)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(Checkbox)
Vue.use(Field)
Vue.use(Form)
Vue.use(Picker)
Vue.use(Popup)
